name: Local AI Code Review
on:
  pull_request:
    types: [opened, synchronized]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Authentication
        run: |
          # Configure git to use HTTP credentials
          git config --global credential.helper store
          echo "http://git:${{ secrets.GITEA_TOKEN }}@172.20.0.2:3000" >> ~/.git-credentials
          chmod 600 ~/.git-credentials
          # Add hosts to /etc/hosts for hostname resolution
          echo "172.20.0.2 gitea" | sudo tee -a /etc/hosts
          echo "172.20.0.3 ollama" | sudo tee -a /etc/hosts

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          fetch-depth: 0

      - name: Get Diff and Review
        run: |
          # 1. Capture the changes in the PR
          git diff HEAD^ HEAD > pr_diff.txt
          
          # 2. Use jq to build a perfectly escaped JSON payload
          # This prevents the "invalid character" errors caused by manual string concatenation
          jq -n \
            --arg model "llama3" \
            --arg diff "$(cat pr_diff.txt)" \
            '{
              model: $model, 
              stream: false, 
              prompt: ("Review this git diff for bugs and security issues. Be concise:\n\n" + $diff)
            }' > /tmp/ollama_request.json
          
          echo "📤 Sending to Ollama at 172.20.0.3:11434..."
          
          # 3. Call Ollama (Using -s to hide progress numbers and -S to show errors)
          RESPONSE_JSON=$(curl -sS -X POST http://172.20.0.3:11434/api/generate \
            --connect-timeout 10 \
            --max-time 60 \
            -H "Content-Type: application/json" \
            -d @/tmp/ollama_request.json)
          
          # 4. Extract the response body safely
          RESPONSE=$(echo "$RESPONSE_JSON" | jq -r '.response // empty')
          
          if [ -z "$RESPONSE" ]; then
            echo "❌ Warning: Could not get valid response from Ollama"
            RESPONSE="AI review service unavailable. Please review the code manually."
          fi

          echo "✅ AI Review completed."
          
          # Export to GITHUB_ENV for the next step
          echo "REVIEW_RESPONSE<<EOF" >> $GITHUB_ENV
          echo "$RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post AI Review as Comment
        if: always()
        run: |
          # Post the review as a comment on the PR
          REVIEW_TEXT="${{ env.REVIEW_RESPONSE }}"
          # Use 'github' context which is standard for Gitea Actions/Runner compatibility
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          TOKEN="${{ secrets.GITEA_TOKEN }}"
          
          echo "Posting comment to: /repos/$OWNER/$REPO/issues/$PR_NUMBER/comments"
          
          # Create JSON payload using jq to handle special characters in the AI's response
          jq -n \
            --arg body "### 🤖 Local AI Code Review${BR}${BR}${REVIEW_TEXT}" \
            '{body: $body}' > /tmp/comment_request.json
          
          curl -sS -X POST "http://172.20.0.2:3000/api/v1/repos/$OWNER/$REPO/issues/$PR_NUMBER/comments" \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d @/tmp/comment_request.json \
            --connect-timeout 10 \
            --max-time 30