name: Local AI Code Review
on:
  pull_request:
    types: [opened, synchronized]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Authentication
        run: |
          # Configure git to use HTTP credentials
          git config --global credential.helper store
          echo "http://git:${{ secrets.GITEA_TOKEN }}@172.20.0.2:3000" >> ~/.git-credentials
          chmod 600 ~/.git-credentials
          # Add hosts to /etc/hosts for hostname resolution
          echo "172.20.0.2 gitea" | sudo tee -a /etc/hosts
          echo "172.20.0.3 ollama" | sudo tee -a /etc/hosts

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          fetch-depth: 0

      - name: Get Diff and Review
        run: |
          # 1. Capture the changes in the PR
          git diff HEAD^ HEAD > pr_diff.txt
          
          # 2. Send the diff to Ollama for review
          # Using IP address 172.20.0.3 (ollama container on docker network)
          RESPONSE=$(curl -s http://172.20.0.3:11434/api/generate \
            --connect-timeout 10 \
            --max-time 60 \
            -d '{
              "model": "llama2",
              "prompt": "Review this git diff for bugs and security issues. Be concise:\n\n'$(cat pr_diff.txt | jq -sRr @json)'",
              "stream": false
            }' | jq -r '.response')

          if [ -z "$RESPONSE" ] || [ "$RESPONSE" == "null" ]; then
            echo "Warning: Could not get response from Ollama"
            RESPONSE="AI review service unavailable. Please review the code manually."
          fi

          echo "AI Review Response: $RESPONSE"
          echo "REVIEW_RESPONSE<<EOF" >> $GITHUB_ENV
          echo "$RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post AI Review as Comment
        if: always()
        run: |
          # Post the review as a comment on the PR
          REVIEW_TEXT="${{ env.REVIEW_RESPONSE }}"
          
          curl -s -X POST "http://172.20.0.2:3000/api/v1/repos/${{ gitea.repository_owner }}/${{ gitea.repository_name }}/issues/${{ gitea.event.pull_request.number }}/comments" \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"### 🤖 Local AI Code Review\n\n$REVIEW_TEXT\"}" \
            --connect-timeout 10 \
            --max-time 30